address: ":8080"
routeRule:
  version: "v1"
  service:
  - name: "test"
    host: 
    - "127.0.0.1:8080"
    endpoint:
    - path: "/v1/*"
      method: "GET"
      backend:
        target:
        - "www.baidu.com"
        scheme: "http"
        tls: false



