
admin:
  address: ":7000"

gateways:
- address: ":8000"

services:
- name: "echo"
  hosts: 
  - "127.0.0.1:8000"
  backends:
  - target: "http://google.com"
  endpoints:
  - path: "/v1/api/echo/*"
    method: "*"
  - path: "/v1/api/echo/hello"
    method: "GET"
  - path: "/v1/api/echo/{name}"
    method: "GET"
  - path: "/v1/api/echo/[a-zA-Z]+"
    method: "GET"
