
admin:
  address: ":7000"

gateways:
- address: ":8000"

services:
- name: "echo"
  hosts: 
  - "localhost"
  - "127.0.0.1"
  endpoints:
  - path: "/v1/echo/*"
    method: "*"
    timeout: "1s"
    middlewares:
      - name: "dyeing"
    backends:
      - target: "www.baidu.com"
