
admin:
  address: ":7000"

gateways:
- address: ":8000"

services:
- name: "echo"
  hosts: 
  - "localhost"
  endpoints:
  - path: "/v1/api/echo/*"
    method: "*"
    timeout: "1s"
    backends:
      - target: "http://google.com"
