
admin:
  address: ":7000"

gateways:
- address: ":8080"

services:
- name: "helloworld"
  hosts: 
  - "localhost"
  - "127.0.0.1"
  middlewares:
  - name: "cors"
  - name: "dyeing"
  endpoints:
  - path: "/helloworld/*"
    method: "*"
    timeout: "1s"
    protocol: "HTTP"
    backends:
    - target: "127.0.0.1:8000"
  - path: "/helloworld.Greeter/*"
    method: "*"
    timeout: "1s"
    protocol: "GRPC"
    backends:
    - target: "127.0.0.1:9000"
