
admin:
  address: ":7000"

gateways:
- address: ":8080"

services:
- name: "helloworld"
  hosts: 
  - "localhost"
  - "127.0.0.1"
  endpoints:
  - path: "/helloworld/*"
    method: "*"
    timeout: "1s"
    middlewares:
      - name: "dyeing"
    backends:
      - target: "127.0.0.1:8000"
    protocol: "HTTP"
  - path: "/helloworld.Greeter/*"
    method: "*"
    timeout: "1s"
    middlewares:
      - name: "dyeing"
    backends:
      - target: "127.0.0.1:9000"
    protocol: "GRPC"
