
gateways:
- address: ":8000"

services:
- name: "echo"
  hosts: 
  - "127.0.0.1:8000"
  backends:
  - target: "http://google.com"
  endpoints:
  - path: "/v1/api/echo/*"
    protocol: "HTTP"
  - path: "/v1/api/echo/hello"
    method: "GET"
    protocol: "HTTP"
  - path: "/v1/api/echo/{name}"
    method: "GET"
    protocol: "HTTP"
  - path: "/v1/api/echo/[a-zA-Z]+"
    method: "GET"
    protocol: "HTTP"
